version: '2'
services:
  postgreshost:
    image: postgres:latest

  postgreshost17:
    image: postgres:latest

  init-postgres:
    image: postgres
    working_dir: /build
    command: sh -c "timeout 10 bash -c '</dev/tcp/postgreshost/5432' 2>/dev/null && (psql -h postgreshost -p 5432 -d postgres -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'django_waitlist_dev'\" | grep -q 1 || psql -h postgreshost -p 5432 -U postgres -c \"CREATE DATABASE django_waitlist_dev\") || echo 'postgreshost failed to start!!!!!'"
    depends_on:
      - postgreshost

  init-postgres17:
    image: postgres
    working_dir: /build
    command: sh -c "timeout 10 bash -c '</dev/tcp/postgreshost17/5432' 2>/dev/null && (psql -h postgreshost17 -p 5432 -d postgres -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'django_waitlist_dev'\" | grep -q 1 || psql -h postgreshost17 -p 5432 -U postgres -c \"CREATE DATABASE django_waitlist_dev\") ||  echo 'postgreshost17 failed to start!!!!!'"
    depends_on:
      - postgreshost17

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.django19
    command: uwsgi --ini uwsgi.ini
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost

  web17:
    build:
      context: .
      dockerfile: docker/Dockerfile.django17
    command: uwsgi --ini uwsgi.ini
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost17:postgreshost

  tcell_web:
    build:
      context: .
      dockerfile: docker/Dockerfile.django19
    command: sh -c "pip install --upgrade tcell_agent && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_local_web:
    build:
      context: .
      dockerfile: docker/Dockerfile.django19
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_local_web_sqlite:
    build:
      context: .
      dockerfile: docker/Dockerfile.django19
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
      - ./docker/settings.py.sqlite:/app/django_waitlist/settings.py
    ports:
      - "3000:3000"
    security_opt:
      - seccomp:unconfined

  tcell_local_web15:
    build:
      context: .
      dockerfile: docker/Dockerfile.django15
    command: sh -c "pip install --upgrade tcell_agent && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
      - ./docker/settings.py.django15:/app/django_waitlist/settings.py
    ports:
      - "3000:3000"
    links:
      - postgreshost17:postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_web17:
    build:
      context: .
      dockerfile: docker/Dockerfile.django17
    command: sh -c "pip install --upgrade tcell_agent && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost17:postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_web17_nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.django17.nginx
    command: /bin/bash -c "service nginx start & sudo -u www-data TCELL_AGENT_HOME=/tmp/tcell tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
      - "80:80"
    links:
      - postgreshost17:postgreshost
    environment:
      - TCELL_AGENT_HOME=/tmp/tcell
    security_opt:
      - seccomp:unconfined

  tcell_web18:
    build:
      context: .
      dockerfile: docker/Dockerfile.django18
    command: sh -c "pip install --upgrade tcell_agent && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_web110:
    build:
      context: .
      dockerfile: docker/Dockerfile.django110
    command: sh -c "pip install --upgrade tcell_agent && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
      - ./docker/settings.py.django110:/app/django_waitlist/settings.py
    ports:
      - "3000:3000"
    links:
      - postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_web110_old_settings:
    build:
      context: .
      dockerfile: docker/Dockerfile.django110
    command: sh -c "pip install --upgrade tcell_agent && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_local_web15:
    build:
      context: .
      dockerfile: docker/Dockerfile.django15
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
      - ./docker/settings.py.django15:/app/django_waitlist/settings.py
    ports:
      - "3000:3000"
    links:
      - postgreshost17:postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_local_web17:
    build:
      context: .
      dockerfile: docker/Dockerfile.django17
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost17:postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_local_web18:
    build:
      context: .
      dockerfile: docker/Dockerfile.django18
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_local_web110:
    build:
      context: .
      dockerfile: docker/Dockerfile.django110
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
      - ./docker/settings.py.django110:/app/django_waitlist/settings.py
    ports:
      - "3000:3000"
    links:
      - postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_local_web110_old_settings:
    build:
      context: .
      dockerfile: docker/Dockerfile.django110
    command: sh -c "pip install --upgrade /tcellagent_src && tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost
    security_opt:
      - seccomp:unconfined

  tcell_web17_newrelic:
    build:
      context: .
      dockerfile: docker/Dockerfile.django17
    command: sh -c "pip install --upgrade tcell_agent && newrelic-admin run-program tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost17:postgreshost
    environment:
      - NEW_RELIC_CONFIG_FILE=newrelic.ini
    security_opt:
      - seccomp:unconfined

  tcell_local_web17_newrelic:
    build:
      context: .
      dockerfile: docker/Dockerfile.django17
    command: sh -c "pip install --upgrade /tcellagent_src && newrelic-admin run-program tcell_agent run uwsgi --ini uwsgi.ini"
    volumes:
      - ../pythonagent-tcell:/tcellagent_src
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgreshost17:postgreshost
    environment:
      - NEW_RELIC_CONFIG_FILE=newrelic.ini
    security_opt:
      - seccomp:unconfined
